### ISSUE TITLE
[Feature Request] Energy (and water) consumption sensor

### ISSUE THREAD

**Issue by catadiel** [HomeAssistant-Mods/home-assistant-miele#58]
Could be nice enabling an energy sensor compatible with the new Home assistant Energy dashboard.
Miele Api provides energy information under the "ecoFeedback" json object.

>the ecoFeedback object returns the amount of water and energy used by the current running program up to the present moment. Furthermore it returns a forecast for water and energy consumption for a selected program.

**Comment by sildehoop** [comment]
I would like that too, and have a temporary solution:

```yaml
template:
  - sensor:
    unique_id: 2fc7dbd7-3201-4067-9256-c7511f6e64fc
    name: Wasmachine Current Energy Consumption
    unit_of_measurement: "kWh"
    state_class: measurement
    device_class: energy
    state: >-
      {{state_attr('sensor.wasmachine_status', 'currentEnergyConsumption')}}
    attributes:
      last_reset: "1970-01-01T00:00:00+00:00"
  - sensor:
      unique_id: e6000881-c024-45ea-b37e-c70bc78ef818
      name: Wasmachine Current Water Consumption
      unit_of_measurement: "L"
      icon: mdi:water
      state: >-
        {{state_attr('sensor.wasmachine_status', 'currentWaterConsumption')}}
```

edit: for it to show up in te energy pannel it needed - state_class and - last_reset

**Comment by slovdahl** [comment]
This sounds interesting!

> I would like that too, and have a temporary solution:
> 
> ```yaml
> template:
>   - sensor:
>     unique_id: 2fc7dbd7-3201-4067-9256-c7511f6e64fc
>     name: Wasmachine Current Energy Consumption
>     unit_of_measurement: "kWh"
>     state_class: measurement
>     device_class: energy
>     state: >-
>       {{state_attr('sensor.wasmachine_status', 'currentEnergyConsumption')}}
>     attributes:
>       last_reset: "1970-01-01T00:00:00+00:00"
>   - sensor:
>       unique_id: e6000881-c024-45ea-b37e-c70bc78ef818
>       name: Wasmachine Current Water Consumption
>       unit_of_measurement: "L"
>       icon: mdi:water
>       state: >-
>         {{state_attr('sensor.wasmachine_status', 'currentWaterConsumption')}}
> ```
> 
> edit: for it to show up in te energy pannel it needed - state_class and - last_reset

Thanks for this! Does the static `last_reset` work properly though? 🤔 AFAICT, the `currentEnergyConsumption` is reset every time the washing machine has run.

Anyway, I started looking into submitting a PR with a fix for this.

**Comment by sildehoop** [comment]
Yes you are right I solved that by a making a utility_meter
```yaml
utility_meters:
  - wasmachine_daily_energy:
    source: sensor.wasmachine_current_energy_consumption
    cycle: daily
```
Now wait a day and see if it works
