### ISSUE TITLE
No "ecoFeedback" with WTR 870 WPM (washer-dryer)

### ISSUE THREAD

**Issue by mundschenk-at** [HomeAssistant-Mods/home-assistant-miele#85]
I recently bought a new washer-dryer WTR 870 WPM  which should support ecoFeedback. However, the generated entities and the attributes of `sensor.<devicename>_status` remain at 0.

```yaml
ProgramID: Dunkle Wäsche
rawProgramID: 50
programType: Eigenes Programm
rawProgramType: 1
programPhase: Waschen
rawProgramPhase: 260
dryingStep: ''
rawDryingStep: 0
spinningSpeed: '1200'
rawSpinningSpeed: 1200
ventilationStep: ''
rawVentilationStep: null
currentWaterConsumption: 0
currentWaterConsumptionUnit: l
currentEnergyConsumption: 0
currentEnergyConsumptionUnit: kWh
waterForecast: 0
energyForecast: 0
progress: 4
finishTime: '12:47'
kickoffTime: '10:18'
friendly_name: Waschtrockner-Status
```
